# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ErrorReport(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, log_name=None, receive_timestamp=None, resource=None, trace=None):  # noqa: E501
        """ErrorReport - a model defined in OpenAPI

        :param id: The id of this ErrorReport.  # noqa: E501
        :type id: str
        :param log_name: The log_name of this ErrorReport.  # noqa: E501
        :type log_name: str
        :param receive_timestamp: The receive_timestamp of this ErrorReport.  # noqa: E501
        :type receive_timestamp: datetime
        :param resource: The resource of this ErrorReport.  # noqa: E501
        :type resource: object
        :param trace: The trace of this ErrorReport.  # noqa: E501
        :type trace: str
        """
        self.openapi_types = {
            'id': str,
            'log_name': str,
            'receive_timestamp': datetime,
            'resource': object,
            'trace': str
        }

        self.attribute_map = {
            'id': 'id',
            'log_name': 'log_name',
            'receive_timestamp': 'receive_timestamp',
            'resource': 'resource',
            'trace': 'trace'
        }

        self._id = id
        self._log_name = log_name
        self._receive_timestamp = receive_timestamp
        self._resource = resource
        self._trace = trace

    @classmethod
    def from_dict(cls, dikt) -> 'ErrorReport':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ErrorReport of this ErrorReport.  # noqa: E501
        :rtype: ErrorReport
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this ErrorReport.


        :return: The id of this ErrorReport.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ErrorReport.


        :param id: The id of this ErrorReport.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def log_name(self):
        """Gets the log_name of this ErrorReport.


        :return: The log_name of this ErrorReport.
        :rtype: str
        """
        return self._log_name

    @log_name.setter
    def log_name(self, log_name):
        """Sets the log_name of this ErrorReport.


        :param log_name: The log_name of this ErrorReport.
        :type log_name: str
        """
        if log_name is None:
            raise ValueError("Invalid value for `log_name`, must not be `None`")  # noqa: E501

        self._log_name = log_name

    @property
    def receive_timestamp(self):
        """Gets the receive_timestamp of this ErrorReport.


        :return: The receive_timestamp of this ErrorReport.
        :rtype: datetime
        """
        return self._receive_timestamp

    @receive_timestamp.setter
    def receive_timestamp(self, receive_timestamp):
        """Sets the receive_timestamp of this ErrorReport.


        :param receive_timestamp: The receive_timestamp of this ErrorReport.
        :type receive_timestamp: datetime
        """
        if receive_timestamp is None:
            raise ValueError("Invalid value for `receive_timestamp`, must not be `None`")  # noqa: E501

        self._receive_timestamp = receive_timestamp

    @property
    def resource(self):
        """Gets the resource of this ErrorReport.


        :return: The resource of this ErrorReport.
        :rtype: object
        """
        return self._resource

    @resource.setter
    def resource(self, resource):
        """Sets the resource of this ErrorReport.


        :param resource: The resource of this ErrorReport.
        :type resource: object
        """
        if resource is None:
            raise ValueError("Invalid value for `resource`, must not be `None`")  # noqa: E501

        self._resource = resource

    @property
    def trace(self):
        """Gets the trace of this ErrorReport.


        :return: The trace of this ErrorReport.
        :rtype: str
        """
        return self._trace

    @trace.setter
    def trace(self, trace):
        """Sets the trace of this ErrorReport.


        :param trace: The trace of this ErrorReport.
        :type trace: str
        """
        if trace is None:
            raise ValueError("Invalid value for `trace`, must not be `None`")  # noqa: E501

        self._trace = trace
# flake8: noqa
