# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class SecurityNotification(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, category=None, created_at=None, exception_instructions=None, explanation=None, external_uri=None, id=None, project_id=None, recommendation=None, resource_name=None, severity=None, updated_at=None):  # noqa: E501
        """SecurityNotification - a model defined in OpenAPI

        :param category: The category of this SecurityNotification.  # noqa: E501
        :type category: str
        :param created_at: The created_at of this SecurityNotification.  # noqa: E501
        :type created_at: datetime
        :param exception_instructions: The exception_instructions of this SecurityNotification.  # noqa: E501
        :type exception_instructions: str
        :param explanation: The explanation of this SecurityNotification.  # noqa: E501
        :type explanation: str
        :param external_uri: The external_uri of this SecurityNotification.  # noqa: E501
        :type external_uri: str
        :param id: The id of this SecurityNotification.  # noqa: E501
        :type id: str
        :param project_id: The project_id of this SecurityNotification.  # noqa: E501
        :type project_id: str
        :param recommendation: The recommendation of this SecurityNotification.  # noqa: E501
        :type recommendation: str
        :param resource_name: The resource_name of this SecurityNotification.  # noqa: E501
        :type resource_name: str
        :param severity: The severity of this SecurityNotification.  # noqa: E501
        :type severity: str
        :param updated_at: The updated_at of this SecurityNotification.  # noqa: E501
        :type updated_at: datetime
        """
        self.openapi_types = {
            'category': str,
            'created_at': datetime,
            'exception_instructions': str,
            'explanation': str,
            'external_uri': str,
            'id': str,
            'project_id': str,
            'recommendation': str,
            'resource_name': str,
            'severity': str,
            'updated_at': datetime
        }

        self.attribute_map = {
            'category': 'category',
            'created_at': 'created_at',
            'exception_instructions': 'exception_instructions',
            'explanation': 'explanation',
            'external_uri': 'external_uri',
            'id': 'id',
            'project_id': 'project_id',
            'recommendation': 'recommendation',
            'resource_name': 'resource_name',
            'severity': 'severity',
            'updated_at': 'updated_at'
        }

        self._category = category
        self._created_at = created_at
        self._exception_instructions = exception_instructions
        self._explanation = explanation
        self._external_uri = external_uri
        self._id = id
        self._project_id = project_id
        self._recommendation = recommendation
        self._resource_name = resource_name
        self._severity = severity
        self._updated_at = updated_at

    @classmethod
    def from_dict(cls, dikt) -> 'SecurityNotification':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SecurityNotification of this SecurityNotification.  # noqa: E501
        :rtype: SecurityNotification
        """
        return util.deserialize_model(dikt, cls)

    @property
    def category(self):
        """Gets the category of this SecurityNotification.


        :return: The category of this SecurityNotification.
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category):
        """Sets the category of this SecurityNotification.


        :param category: The category of this SecurityNotification.
        :type category: str
        """

        self._category = category

    @property
    def created_at(self):
        """Gets the created_at of this SecurityNotification.


        :return: The created_at of this SecurityNotification.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this SecurityNotification.


        :param created_at: The created_at of this SecurityNotification.
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def exception_instructions(self):
        """Gets the exception_instructions of this SecurityNotification.


        :return: The exception_instructions of this SecurityNotification.
        :rtype: str
        """
        return self._exception_instructions

    @exception_instructions.setter
    def exception_instructions(self, exception_instructions):
        """Sets the exception_instructions of this SecurityNotification.


        :param exception_instructions: The exception_instructions of this SecurityNotification.
        :type exception_instructions: str
        """

        self._exception_instructions = exception_instructions

    @property
    def explanation(self):
        """Gets the explanation of this SecurityNotification.


        :return: The explanation of this SecurityNotification.
        :rtype: str
        """
        return self._explanation

    @explanation.setter
    def explanation(self, explanation):
        """Sets the explanation of this SecurityNotification.


        :param explanation: The explanation of this SecurityNotification.
        :type explanation: str
        """

        self._explanation = explanation

    @property
    def external_uri(self):
        """Gets the external_uri of this SecurityNotification.


        :return: The external_uri of this SecurityNotification.
        :rtype: str
        """
        return self._external_uri

    @external_uri.setter
    def external_uri(self, external_uri):
        """Sets the external_uri of this SecurityNotification.


        :param external_uri: The external_uri of this SecurityNotification.
        :type external_uri: str
        """

        self._external_uri = external_uri

    @property
    def id(self):
        """Gets the id of this SecurityNotification.


        :return: The id of this SecurityNotification.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SecurityNotification.


        :param id: The id of this SecurityNotification.
        :type id: str
        """

        self._id = id

    @property
    def project_id(self):
        """Gets the project_id of this SecurityNotification.


        :return: The project_id of this SecurityNotification.
        :rtype: str
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this SecurityNotification.


        :param project_id: The project_id of this SecurityNotification.
        :type project_id: str
        """

        self._project_id = project_id

    @property
    def recommendation(self):
        """Gets the recommendation of this SecurityNotification.


        :return: The recommendation of this SecurityNotification.
        :rtype: str
        """
        return self._recommendation

    @recommendation.setter
    def recommendation(self, recommendation):
        """Sets the recommendation of this SecurityNotification.


        :param recommendation: The recommendation of this SecurityNotification.
        :type recommendation: str
        """

        self._recommendation = recommendation

    @property
    def resource_name(self):
        """Gets the resource_name of this SecurityNotification.


        :return: The resource_name of this SecurityNotification.
        :rtype: str
        """
        return self._resource_name

    @resource_name.setter
    def resource_name(self, resource_name):
        """Sets the resource_name of this SecurityNotification.


        :param resource_name: The resource_name of this SecurityNotification.
        :type resource_name: str
        """

        self._resource_name = resource_name

    @property
    def severity(self):
        """Gets the severity of this SecurityNotification.


        :return: The severity of this SecurityNotification.
        :rtype: str
        """
        return self._severity

    @severity.setter
    def severity(self, severity):
        """Sets the severity of this SecurityNotification.


        :param severity: The severity of this SecurityNotification.
        :type severity: str
        """

        self._severity = severity

    @property
    def updated_at(self):
        """Gets the updated_at of this SecurityNotification.


        :return: The updated_at of this SecurityNotification.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this SecurityNotification.


        :param updated_at: The updated_at of this SecurityNotification.
        :type updated_at: datetime
        """

        self._updated_at = updated_at
# flake8: noqa
