---
timeout: 1800s
steps:

# Deploying the Cloud Function
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud functions deploy ${PROJECT_ID}-error-notifier-func \
      --entry-point=error_to_notification \
      --runtime=python37 \
      --trigger-http \
      --project=${PROJECT_ID} \
      --region=europe-west1 \
      --max-instances=1
    gcloud functions add-iam-policy-binding ${PROJECT_ID}-error-notifier-func \
      --region=europe-west1 \
      --member="serviceAccount:${PROJECT_ID}@appspot.gserviceaccount.com" \
      --role="roles/cloudfunctions.invoker"

# Deploying the Cloud Scheduler
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud scheduler jobs delete ${PROJECT_ID}-errornotifier-job --quiet || true
    gcloud scheduler jobs create http ${PROJECT_ID}-errornotifier-job \
      --schedule="0 * * * *" \
      --uri=https://europe-west1-${PROJECT_ID}.cloudfunctions.net/${PROJECT_ID}-error-notifier-func/ \
      --http-method=POST \
      --message-body="{\"interval\": 60}" \
      --oidc-service-account-email=${PROJECT_ID}@appspot.gserviceaccount.com \
      --oidc-token-audience=https://europe-west1-${PROJECT_ID}.cloudfunctions.net/${PROJECT_ID}-error-notifier-func
