openapi: 3.0.2
x-zally-ignore: [110, 105, 104, 101]
info:
  contact:
    email: opensource@vwt.digital
    name: VolkerWessels Telecom - Digital Ambition Team
    url: https://vwt-digital.github.io/
  description: Endpoint to retreive all DAT Monitoring metrics
  license:
    name: GNU GPLv3
    url: https://www.gnu.org/licenses/gpl.txt
  title: Monitoring
  version: 1.0.0
  x-audience: company-internal
  x-api-id: unspecified
servers:
- url: https://PROJECT_ID.appspot.com/
security:
- ApiKeyAuth: []
paths:
  /build-statuses-triggers:
    get:
      description: Get a list of all build trigger statuses
      operationId: build_statuses_triggers_get
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/BuildTriggerStatus'
                type: array
          description: Scheme with multiple build trigger statuses
        "204":
          description: No content
      summary: Get all build trigger statuses
      x-openapi-router-controller: openapi_server.controllers.buildstatuses_controller
  /error-reports:
    get:
      description: Get a list of errors reportings
      operationId: error_reports_get
      parameters:
      - description: The numbers of items within a page.
        explode: true
        in: query
        name: pageSize
        required: false
        schema:
          default: 50
          maximum: 100
          minimum: 1
          type: integer
        style: form
      - description: The query cursor of the page
        explode: true
        in: query
        name: cursor
        required: false
        schema:
          type: string
          format: byte
        style: form
      - description: Selector to get next or previous page based on the cursor
        explode: true
        in: query
        name: page
        required: false
        schema:
          default: next
          enum:
          - prev
          - next
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ErrorReportResponse'
                type: array
          description: Scheme with multiple error reportings
        "204":
          description: No content
      summary: Get errors reportings
      x-openapi-router-controller: openapi_server.controllers.errorreporting_controller
  /error-reports/counts:
    get:
      description: Get a list of projects with errors reportings count in last x days
      operationId: error_reports_counts_get
      parameters:
      - description: Total days to include
        explode: true
        in: query
        name: days
        required: false
        schema:
          default: 7
          minimum: 1
          type: integer
        style: form
      - description: Max rows to return
        explode: true
        in: query
        name: max_rows
        required: false
        schema:
          default: 5
          minimum: 1
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ErrorReportCount'
                type: array
          description: Scheme with count of error reportings per project
        "204":
          description: No content
        "403":
          description: Parameters must be more than 0
      summary: Get count of project errors reportings in last x days
      x-openapi-router-controller: openapi_server.controllers.errorreporting_controller
components:
  parameters:
    pageSizeParam:
      description: The numbers of items within a page.
      explode: true
      in: query
      name: pageSize
      required: false
      schema:
        default: 50
        maximum: 100
        minimum: 1
        type: integer
      style: form
    cursorParam:
      description: The query cursor of the page
      explode: true
      in: query
      name: cursor
      required: false
      schema:
        type: string
        format: byte
      style: form
    pageParam:
      description: Selector to get next or previous page based on the cursor
      explode: true
      in: query
      name: page
      required: false
      schema:
        default: next
        enum:
        - prev
        - next
        type: string
      style: form
  responses:
    BuildTriggerStatuses:
      content:
        application/json:
          schema:
            items:
              $ref: '#/components/schemas/BuildTriggerStatus'
            type: array
      description: Scheme with multiple build trigger statuses
    ErrorReporting:
      content:
        application/json:
          schema:
            items:
              $ref: '#/components/schemas/ErrorReportResponse'
            type: array
      description: Scheme with multiple error reportings
    ErrorReportingCount:
      content:
        application/json:
          schema:
            items:
              $ref: '#/components/schemas/ErrorReportCount'
            type: array
      description: Scheme with count of error reportings per project
  schemas:
    BuildTriggerStatus:
      example:
        branch: develop
        project_id: random-project-id
        repo_name: random-repo-name
        status: passing
        updated: 2019-09-01T12:00:00+02:00
        log_url: https://console.cloud.google.com/gcr/builds/random-project-id
      properties:
        branch:
          type: string
        project_id:
          type: string
        repo_name:
          type: string
        status:
          enum:
          - pending
          - failing
          - passing
          type: string
        updated:
          format: date-time
          type: string
        log_url:
          type: string
      required:
      - branch
      - log_url
      - project_id
      - repo_name
      - status
      - updated
      type: object
    ErrorReport:
      example:
        id: 1a9390e9-4ac5-4527-8e5e-05d2d153ada0
        labels: {}
        log_name: random-log-name
        project_id: random-project-id
        receive_timestamp: 2019-09-01T12:00:00+02:00
        resource: {}
        severity: ERROR
        text_payload: This is a payload
        trace: random-trace
      properties:
        id:
          type: string
        labels:
          type: object
        log_name:
          type: string
        project_id:
          type: string
        receive_timestamp:
          format: date-time
          type: string
        resource:
          type: object
        severity:
          type: string
        text_payload:
          type: string
        trace:
          type: string
      required:
      - id
      - project_id
      - receive_timestamp
      type: object
    ErrorReportCount:
      example:
        count: 123
        latest_updated: 2019-09-01T12:00:00+02:00
        project_id: random-project-id
        resource:
          type: application
      properties:
        count:
          format: int32
          type: integer
        latest_updated:
          format: date-time
          type: string
        project_id:
          type: string
        resource:
          type: object
      required:
      - count
      - latest_updated
      - project_id
      - resource
      type: object
    ErrorReportResponse:
      example:
        status: Success
        page_size: 50
        next_cursor: eee028e4-ef38-40fb-a92b-41c441660d2e
        results:
        - id: 1a9390e9-4ac5-4527-8e5e-05d2d153ada0
          labels: {}
          log_name: random-log-name
          project_id: random-project-id
          receive_timestamp: 2019-09-01T12:00:00+02:00
          resource: {}
          severity: ERROR
          text_payload: This is a payload
          trace: random-trace
      properties:
        status:
          description: The request status.
          type: string
        page_size:
          description: The current page size
          type: integer
        next_cursor:
          description: The next query cursor
          type: string
          format: byte
        results:
          items:
            $ref: '#/components/schemas/ErrorReport'
          type: array
      type: object
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: X-API-KEY
      type: apiKey
      x-apikeyInfoFunc: openapi_server.controllers.security_controller_.info_from_ApiKeyAuth
