openapi: 3.0.1
info:
  contact:
    email: opensource@vwt.digital
    name: VolkerWessels Telecom - Digital Ambition Team
    url: https://vwt-digital.github.io/
  description: Endpoint to retreive all DAT Monitoring metrics
  license:
    name: GNU GPLv3
    url: https://www.gnu.org/licenses/gpl.txt
  title: Monitoring
  version: 1.0.0
servers:
- url: https://vwt-d-gew1-dat-monitoring.appspot.com/
security:
- ApiKeyAuth: []
paths:
  /build-statuses:
    get:
      description: Get a list of all build statuses
      operationId: build_statuses_get
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/BuildStatus'
                type: array
          description: Scheme with multiple build statuses
        204:
          content: {}
          description: No content
      summary: Get all build statuses
      x-openapi-router-controller: openapi_server.controllers.buildstatuses_controller
  /build-statuses/branch/{branch}:
    get:
      description: Get a list of all build statuses from a specific branch
      operationId: build_statuses_branch_branch_get
      parameters:
      - description: A unique branch identifier
        in: path
        name: branch
        required: true
        schema:
          enum:
          - master
          - develop
          type: string
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/BuildStatus'
                type: array
          description: Scheme with multiple build statuses
        204:
          content: {}
          description: No content
        404:
          content: {}
          description: Branch not of correct type
      summary: Get all branch build statuses
      x-openapi-router-controller: openapi_server.controllers.buildstatuses_controller
  /build-statuses/project/{project_id}:
    get:
      description: Get a list of all build statuses from a specific project
      operationId: build_statuses_project_project_id_get
      parameters:
      - description: A unique project identifier
        in: path
        name: project_id
        required: true
        schema:
          type: string
      - description: A specific branch
        in: query
        name: branch
        schema:
          enum:
          - master
          - develop
          type: string
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/BuildStatus'
                type: array
          description: Scheme with multiple build statuses
        204:
          content: {}
          description: No content
        404:
          content: {}
          description: Branch not of correct type
      summary: Get all project build statuses
      x-openapi-router-controller: openapi_server.controllers.buildstatuses_controller
components:
  schemas:
    BuildStatus:
      example:
        branch: develop
        git_source: github
        organization: vwt-digital
        project_id: random-project-id
        repo_name: random-repo-name
        status: passing
        updated: 2019-09-01T10:00:00.000+0000
      properties:
        branch:
          type: string
        git_source:
          type: string
        organization:
          type: string
        project_id:
          type: string
        repo_name:
          type: string
        status:
          enum:
          - pending
          - failing
          - passing
          type: string
        updated:
          format: date-time
          type: string
      required:
      - branch
      - git_source
      - organization
      - project_id
      - repo_name
      - status
      - updated
      type: object
  securitySchemes:
    ApiKeyAuth:
      in: query
      name: key
      type: apiKey
      x-apikeyInfoFunc: openapi_server.controllers.security_controller_.info_from_ApiKeyAuth
