openapi: 3.0.2
info:
  contact:
    email: opensource@vwt.digital
    name: VolkerWessels Telecom - Digital Ambition Team
    url: https://vwt-digital.github.io/
  description: Endpoint to retreive all DAT Monitoring metrics
  license:
    name: GNU GPLv3
    url: https://www.gnu.org/licenses/gpl.txt
  title: Monitoring
  version: 1.0.0
servers:
- url: https://PROJECT_ID.appspot.com/
security:
- ApiKeyAuth: []
paths:
  /build-statuses-other:
    get:
      description: Get a list of all other build statuses
      operationId: build_statuses_other_get
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/BuildOtherStatus'
                type: array
          description: Scheme with multiple other build statuses
        204:
          description: No content
      summary: Get all other build statuses
      x-openapi-router-controller: openapi_server.controllers.buildstatuses_controller
  /build-statuses-other/{status}:
    get:
      description: Get a list of all other build statuses with a specific status
      operationId: build_statuses_other_status_get
      parameters:
      - description: A unique status identifier
        explode: false
        in: path
        name: status
        required: true
        schema:
          enum:
          - failing
          - pending
          - passing
          type: string
        style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/BuildOtherStatus'
                type: array
          description: Scheme with multiple other build statuses
        204:
          description: No content
        404:
          description: Status not of correct type
      summary: Get all other build statuses by status
      x-openapi-router-controller: openapi_server.controllers.buildstatuses_controller
  /build-statuses-triggers:
    get:
      description: Get a list of all build trigger statuses
      operationId: build_statuses_triggers_get
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/BuildTriggerStatus'
                type: array
          description: Scheme with multiple build trigger statuses
        204:
          description: No content
      summary: Get all build trigger statuses
      x-openapi-router-controller: openapi_server.controllers.buildstatuses_controller
  /build-statuses-triggers/branch/{branch}:
    get:
      description: Get a list of all build trigger statuses from a specific branch
      operationId: build_statuses_triggers_branch_branch_get
      parameters:
      - description: A unique branch identifier
        explode: false
        in: path
        name: branch
        required: true
        schema:
          enum:
          - master
          - develop
          type: string
        style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/BuildTriggerStatus'
                type: array
          description: Scheme with multiple build trigger statuses
        204:
          description: No content
        404:
          description: Branch not of correct type
      summary: Get all build trigger statuses by branch
      x-openapi-router-controller: openapi_server.controllers.buildstatuses_controller
components:
  responses:
    BuildTriggerStatuses:
      content:
        application/json:
          schema:
            items:
              $ref: '#/components/schemas/BuildTriggerStatus'
            type: array
      description: Scheme with multiple build trigger statuses
    BuildOtherStatuses:
      content:
        application/json:
          schema:
            items:
              $ref: '#/components/schemas/BuildOtherStatus'
            type: array
      description: Scheme with multiple other build statuses
  schemas:
    BuildTriggerStatus:
      example:
        branch: develop
        git_source: github
        organization: vwt-digital
        project_id: random-project-id
        repo_name: random-repo-name
        status: passing
        updated: 2019-09-01T12:00:00+02:00
      properties:
        branch:
          type: string
        git_source:
          type: string
        organization:
          type: string
        project_id:
          type: string
        repo_name:
          type: string
        status:
          enum:
          - pending
          - failing
          - passing
          type: string
        updated:
          format: date-time
          type: string
      required:
      - branch
      - git_source
      - organization
      - project_id
      - repo_name
      - status
      - updated
      type: object
    BuildOtherStatus:
      example:
        finish_time: 2019-09-01T12:00:00+02:00
        start_time: 2019-09-01T12:00:00+02:00
        id: 918d693e-7cc1-45f7-bde2-e00cca32a5b1
        project_id: random-project-id
        status: passing
      properties:
        finish_time:
          format: date-time
          type: string
        start_time:
          format: date-time
          type: string
        id:
          format: uuid
          type: string
        project_id:
          type: string
        status:
          enum:
          - pending
          - failing
          - passing
          type: string
      required:
      - finish_time
      - id
      - project_id
      - start_time
      - status
      type: object
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: X-API-KEY
      type: apiKey
      x-apikeyInfoFunc: openapi_server.controllers.security_controller_.info_from_ApiKeyAuth
