openapi: 3.0.2
info:
  contact:
    email: opensource@vwt.digital
    name: VolkerWessels Telecom - Digital Ambition Team
    url: https://vwt-digital.github.io/
  description: Endpoint to retreive all DAT Monitoring metrics
  license:
    name: GNU GPLv3
    url: https://www.gnu.org/licenses/gpl.txt
  title: Monitoring
  version: 1.0.0
servers:
- url: https://PROJECT_ID.appspot.com/
security:
- ApiKeyAuth: []
paths:
  /build-statuses-other:
    get:
      description: Get a list of last 20 other build statuses
      operationId: build_statuses_other_get
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/BuildOtherStatus'
                type: array
          description: Scheme with multiple other build statuses
        204:
          description: No content
      summary: Get last 20 other build statuses
      x-openapi-router-controller: openapi_server.controllers.buildstatuses_controller
  /build-statuses-other/{status}:
    get:
      description: Get a list of other build statuses by status, days and max rows
      operationId: build_statuses_other_status_get
      parameters:
      - description: A unique status identifier
        explode: false
        in: path
        name: status
        required: true
        schema:
          enum:
          - failing
          - pending
          - passing
          type: string
        style: simple
      - description: Total days to include
        explode: true
        in: query
        name: days
        required: false
        schema:
          default: 7
          type: integer
        style: form
      - description: Max rows to return
        explode: true
        in: query
        name: maxRows
        required: false
        schema:
          default: 20
          type: integer
        style: form
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/BuildOtherStatus'
                type: array
          description: Scheme with multiple other build statuses
        204:
          description: No content
        404:
          description: Status not of correct type
      summary: Get other build statuses by conditions
      x-openapi-router-controller: openapi_server.controllers.buildstatuses_controller
  /build-statuses-triggers:
    get:
      description: Get a list of all build trigger statuses
      operationId: build_statuses_triggers_get
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/BuildTriggerStatus'
                type: array
          description: Scheme with multiple build trigger statuses
        204:
          description: No content
      summary: Get all build trigger statuses
      x-openapi-router-controller: openapi_server.controllers.buildstatuses_controller
  /error-reporting:
    get:
      description: Get a list of errors reportings by days and max rows
      operationId: error_reporting_get
      parameters:
      - description: Total days to include
        explode: true
        in: query
        name: days
        required: false
        schema:
          default: 7
          type: integer
        style: form
      - description: Max rows to return
        explode: true
        in: query
        name: maxRows
        required: false
        schema:
          default: 20
          type: integer
        style: form
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ErrorReport'
                type: array
          description: Scheme with multiple error reportings
        204:
          description: No content
      summary: Get errors reportings by conditions
      x-openapi-router-controller: openapi_server.controllers.errorreporting_controller
  /error-reporting/count:
    get:
      description: Get a list of projects with errors reportings count in last 7 days
      operationId: error_reporting_count_get
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ErrorReportCount'
                type: array
          description: Scheme with count of error reportings per project
        204:
          description: No content
      summary: Get count of project errors reportings in last 7 days
      x-openapi-router-controller: openapi_server.controllers.errorreporting_controller
components:
  responses:
    BuildTriggerStatuses:
      content:
        application/json:
          schema:
            items:
              $ref: '#/components/schemas/BuildTriggerStatus'
            type: array
      description: Scheme with multiple build trigger statuses
    BuildOtherStatuses:
      content:
        application/json:
          schema:
            items:
              $ref: '#/components/schemas/BuildOtherStatus'
            type: array
      description: Scheme with multiple other build statuses
    ErrorReporting:
      content:
        application/json:
          schema:
            items:
              $ref: '#/components/schemas/ErrorReport'
            type: array
      description: Scheme with multiple error reportings
    ErrorReportingCount:
      content:
        application/json:
          schema:
            items:
              $ref: '#/components/schemas/ErrorReportCount'
            type: array
      description: Scheme with count of error reportings per project
  schemas:
    BuildTriggerStatus:
      example:
        branch: develop
        project_id: random-project-id
        repo_name: random-repo-name
        status: passing
        updated: 2019-09-01T12:00:00+02:00
        log_url: https://console.cloud.google.com/gcr/builds/random-project-id
      properties:
        branch:
          type: string
        project_id:
          type: string
        repo_name:
          type: string
        status:
          enum:
          - pending
          - failing
          - passing
          type: string
        updated:
          format: date-time
          type: string
        log_url:
          type: string
      required:
      - branch
      - log_url
      - project_id
      - repo_name
      - status
      - updated
      type: object
    BuildOtherStatus:
      example:
        finish_time: 2019-09-01T12:00:00+02:00
        start_time: 2019-09-01T12:00:00+02:00
        id: 918d693e-7cc1-45f7-bde2-e00cca32a5b1
        project_id: random-project-id
        status: passing
        log_url: https://console.cloud.google.com/gcr/builds/918d693e-7cc1-45f7-bde2-e00cca32a5b1
      properties:
        finish_time:
          format: date-time
          type: string
        start_time:
          format: date-time
          type: string
        id:
          format: uuid
          type: string
        project_id:
          type: string
        status:
          enum:
          - pending
          - failing
          - passing
          type: string
        log_url:
          type: string
      required:
      - finish_time
      - id
      - log_url
      - project_id
      - start_time
      - status
      type: object
    ErrorReport:
      example:
        id: 1a9390e9-4ac5-4527-8e5e-05d2d153ada0
        log_name: random-log-name
        receive_timestamp: 2019-09-01T12:00:00+02:00
        resource: {}
        trace: random-trace
      properties:
        id:
          type: string
        log_name:
          type: string
        receive_timestamp:
          format: date-time
          type: string
        resource:
          type: object
        trace:
          type: string
      required:
      - id
      - log_name
      - receive_timestamp
      - resource
      - trace
      type: object
    ErrorReportCount:
      example:
        count: 123
        latest_updated: 2019-09-01T12:00:00+02:00
        project_id: random-project-id
        resource:
          type: application
      properties:
        count:
          type: integer
        latest_updated:
          format: date-time
          type: string
        project_id:
          type: string
        resource:
          type: object
      required:
      - count
      - latest_updated
      - project_id
      - resource
      type: object
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: X-API-KEY
      type: apiKey
      x-apikeyInfoFunc: openapi_server.controllers.security_controller_.info_from_ApiKeyAuth
