openapi: 3.0.2
x-zally-ignore: [101, 104, 105, 110, 150, 235]
info:
  contact:
    email: opensource@vwt.digital
    name: VolkerWessels Telecom - Digital Ambition Team
    url: https://vwt-digital.github.io/
  description: Endpoint to retreive all DAT Monitoring metrics
  license:
    name: GNU GPLv3
    url: https://www.gnu.org/licenses/gpl.txt
  title: Monitoring
  version: 1.0.0
  x-audience: company-internal
  x-api-id: unspecified
servers:
- url: https://PROJECT_ID.appspot.com/
security:
- ApiKeyAuth: []
paths:
  /build-statuses-triggers:
    get:
      description: Get a list of all build trigger statuses
      operationId: build_statuses_triggers_get
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/BuildTriggerStatus'
                type: array
          description: Scheme with multiple build trigger statuses
        "204":
          description: No content
        "400":
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Bad Request
        "401":
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: No authorization token provided
        "403":
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Provided token doesn't have the required scope
      summary: Get all build trigger statuses
      x-openapi-router-controller: openapi_server.controllers.buildstatuses_controller
  /error-reports:
    get:
      description: Get a list of errors reportings
      operationId: error_reports_get
      parameters:
      - description: The numbers of items within a page.
        explode: true
        in: query
        name: page_size
        required: false
        schema:
          default: 50
          maximum: 100
          minimum: 1
          type: integer
        style: form
      - description: The query cursor of the page
        explode: true
        in: query
        name: cursor
        required: false
        schema:
          type: string
          format: byte
        style: form
      - description: Selector to get next or previous page based on the cursor
        explode: true
        in: query
        name: page
        required: false
        schema:
          default: next
          enum:
          - prev
          - next
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ErrorReportResponse'
                type: array
          description: Scheme with multiple error reportings
        "204":
          description: No content
        "400":
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Bad Request
        "401":
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: No authorization token provided
        "403":
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Provided token doesn't have the required scope
      summary: Get errors reportings
      x-openapi-router-controller: openapi_server.controllers.errorreporting_controller
  /error-reports/counts:
    get:
      description: Get a list of projects with errors reportings count in last x days
      operationId: error_reports_counts_get
      parameters:
      - description: Total days to include
        explode: true
        in: query
        name: days
        required: false
        schema:
          default: 7
          minimum: 1
          type: integer
        style: form
      - description: Max rows to return
        explode: true
        in: query
        name: max_rows
        required: false
        schema:
          default: 5
          minimum: 1
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ErrorReportCount'
                type: array
          description: Scheme with count of error reportings per project
        "204":
          description: No content
        "400":
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Bad Request
        "401":
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: No authorization token provided
        "403":
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Provided token doesn't have the required scope
      summary: Get count of project errors reportings in last x days
      x-openapi-router-controller: openapi_server.controllers.errorreporting_controller
  /security-notifications:
    get:
      description: Get a list of security notifications in last x days
      operationId: security_notifications_get
      parameters:
        - description: Total days to include
          explode: true
          in: query
          name: days
          required: false
          schema:
            minimum: 1
            type: integer
          style: form
        - description: Max rows to return
          explode: true
          in: query
          name: max_rows
          required: false
          schema:
            default: 5
            minimum: 1
            maximum: 100
            type: integer
          style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/SecurityNotification'
                type: array
          description: Scheme with security notifications
        "204":
          description: No content
        "400":
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Bad Request
        "401":
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: No authorization token provided
        "403":
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Provided token doesn't have the required scope
      summary: Get a list of security notifications in last x days
      x-openapi-router-controller: openapi_server.controllers.errorreporting_controller
components:
  parameters:
    pageSizeParam:
      description: The numbers of items within a page.
      explode: true
      in: query
      name: page_size
      required: false
      schema:
        default: 50
        maximum: 100
        minimum: 1
        type: integer
      style: form
    cursorParam:
      description: The query cursor of the page
      explode: true
      in: query
      name: cursor
      required: false
      schema:
        type: string
        format: byte
      style: form
    pageParam:
      description: Selector to get next or previous page based on the cursor
      explode: true
      in: query
      name: page
      required: false
      schema:
        default: next
        enum:
        - prev
        - next
        type: string
      style: form
  responses:
    BuildTriggerStatuses:
      content:
        application/json:
          schema:
            items:
              $ref: '#/components/schemas/BuildTriggerStatus'
            type: array
      description: Scheme with multiple build trigger statuses
    ErrorReporting:
      content:
        application/json:
          schema:
            items:
              $ref: '#/components/schemas/ErrorReportResponse'
            type: array
      description: Scheme with multiple error reportings
    ErrorReportingCount:
      content:
        application/json:
          schema:
            items:
              $ref: '#/components/schemas/ErrorReportCount'
            type: array
      description: Scheme with count of error reportings per project
  schemas:
    BuildTriggerStatus:
      example:
        branch: develop
        project_id: random-project-id
        repo_name: random-repo-name
        status: passing
        updated_at: 2019-09-01T12:00:00+02:00
        log_url: https://console.cloud.google.com/gcr/builds/random-project-id
      properties:
        branch:
          type: string
        project_id:
          type: string
        repo_name:
          type: string
        status:
          enum:
          - pending
          - failing
          - passing
          type: string
        updated_at:
          format: date-time
          type: string
        log_url:
          type: string
      required:
      - branch
      - log_url
      - project_id
      - repo_name
      - status
      - updated_at
      type: object
    ErrorReport:
      example:
        id: 1a9390e9-4ac5-4527-8e5e-05d2d153ada0
        labels: {}
        log_name: random-log-name
        project_id: random-project-id
        received_at: 2019-09-01T12:00:00+02:00
        resource: {}
        severity: ERROR
        text_payload: This is a payload
        trace: random-trace
      properties:
        id:
          type: string
        labels:
          type: object
        log_name:
          type: string
        project_id:
          type: string
        received_at:
          format: date-time
          type: string
        resource:
          type: object
        severity:
          type: string
        text_payload:
          type: string
        trace:
          type: string
      required:
      - id
      - project_id
      - received_at
      type: object
    ErrorReportCount:
      example:
        count: 123
        updated_at: 2019-09-01T12:00:00+02:00
        project_id: random-project-id
        resource:
          type: application
      properties:
        count:
          format: int32
          type: integer
        updated_at:
          format: date-time
          type: string
        project_id:
          type: string
        resource:
          type: object
      required:
      - count
      - updated_at
      - project_id
      - resource
      type: object
    ErrorReportResponse:
      example:
        status: Success
        page_size: 50
        next_cursor: eee028e4-ef38-40fb-a92b-41c441660d2e
        results:
        - id: 1a9390e9-4ac5-4527-8e5e-05d2d153ada0
          labels: {}
          log_name: random-log-name
          project_id: random-project-id
          received_at: 2019-09-01T12:00:00+02:00
          resource: {}
          severity: ERROR
          text_payload: This is a payload
          trace: random-trace
      properties:
        status:
          description: The request status.
          type: string
        page_size:
          description: The current page size
          format: int32
          type: integer
        next_cursor:
          description: The next query cursor
          type: string
          format: byte
        results:
          items:
            $ref: '#/components/schemas/ErrorReport'
          type: array
      type: object
    SecurityNotification:
      example:
        category: Security issue
        created_at: 2020-01-01T12:00:00.000Z
        exception_instructions: A security error occurred
        explanation: You did something wrong
        external_uri: https://external-uri.com/
        id: 9f85595a-906f-4d48-b3da-94920c586bf4
        project_id: project_x
        recommendation: Try to fix it
        resource_name: resource_y
        severity: High
        updated_at: 2020-01-01T12:05:00.000Z
      properties:
        category:
          type: string
        created_at:
          format: date-time
          type: string
        exception_instructions:
          type: string
        explanation:
          type: string
        external_uri:
          type: string
        id:
          type: string
        project_id:
          type: string
        recommendation:
          type: string
        resource_name:
          type: string
        severity:
          type: string
        updated_at:
          format: date-time
          type: string
      type: object
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: X-API-KEY
      type: apiKey
      x-apikeyInfoFunc: openapi_server.controllers.security_controller_.info_from_ApiKeyAuth
