---
openapi: 3.0.2
info:
  title: Monitoring
  version: 1.0.0
  description: Endpoint to retreive all DAT Monitoring metrics
  contact:
    name: VolkerWessels Telecom - Digital Ambition Team
    url: 'https://vwt-digital.github.io/'
    email: opensource@vwt.digital
  license:
    name: GNU GPLv3
    url: 'https://www.gnu.org/licenses/gpl.txt'
servers:
- url: 'https://PROJECT_ID.appspot.com/'
  description: ""
security:
  - ApiKeyAuth: []
paths:
  /build-statuses-triggers:
    get:
      responses:
        200:
          $ref: '#/components/responses/BuildTriggerStatuses'
        204:
          description: No content
      summary: Get all build trigger statuses
      description: Get a list of all build trigger statuses
      x-openapi-router-controller: openapi_server.controllers.buildstatuses_controller
  /build-statuses-other:
    get:
      responses:
        200:
          $ref: '#/components/responses/BuildOtherStatuses'
        204:
          description: No content
      summary: Get last 20 other build statuses
      description: Get a list of last 20 other build statuses
      x-openapi-router-controller: openapi_server.controllers.buildstatuses_controller
  /build-statuses-other/{status}:
    get:
      responses:
        200:
          $ref: '#/components/responses/BuildOtherStatuses'
        204:
          description: No content
        404:
          description: Status not of correct type
      summary: Get other build statuses by conditions
      description: Get a list of other build statuses by status, days and max rows
      parameters:
        - name: status
          in: path
          description: A unique status identifier
          required: True
          schema:
              type: string
              enum: [failing, pending, passing]
        - name: days
          in: query
          description: Total days to include
          schema:
              type: integer
              default: 7
        - name: maxRows
          in: query
          description: Max rows to return
          schema:
              type: integer
              default: 20
      x-openapi-router-controller: openapi_server.controllers.buildstatuses_controller
  /error-reporting:
    get:
      responses:
        200:
          $ref: '#/components/responses/ErrorReporting'
        204:
          description: No content
      summary: Get errors reportings by conditions
      description: Get a list of errors reportings by days and max rows
      parameters:
        - name: days
          in: query
          description: Total days to include
          schema:
              type: integer
              default: 7
        - name: maxRows
          in: query
          description: Max rows to return
          schema:
              type: integer
              default: 20
      x-openapi-router-controller: openapi_server.controllers.errorreporting_controller
  /error-reporting/count:
    get:
      responses:
        200:
          $ref: '#/components/responses/ErrorReportingCount'
        204:
          description: No content
      summary: Get count of project errors reportings in last 7 days
      description: Get a list of projects with errors reportings count in last 7 days
      x-openapi-router-controller: openapi_server.controllers.errorreporting_controller
components:
  schemas:
    BuildTriggerStatus:
      required:
      - branch
      - project_id
      - repo_name
      - status
      - updated
      - log_url
      type: object
      properties:
        branch:
          type: string
        project_id:
          type: string
        repo_name:
          type: string
        status:
          enum:
          - pending
          - failing
          - passing
          type: string
        updated:
          format: date-time
          type: string
        log_url:
          type: string
      example:
        branch: develop
        project_id: random-project-id
        repo_name: random-repo-name
        status: passing
        updated: 2019-09-01T12:00:00+02:00
        log_url: https://console.cloud.google.com/gcr/builds/random-project-id
    BuildOtherStatus:
      required:
      - finish_time
      - start_time
      - id
      - project_id
      - status
      - log_url
      type: object
      properties:
        finish_time:
          format: date-time
          type: string
        start_time:
          format: date-time
          type: string
        id:
          type: string
          format: uuid
        project_id:
          type: string
        status:
          enum:
          - pending
          - failing
          - passing
          type: string
        log_url:
          type: string
      example:
        finish_time: 2019-09-01T12:00:00+02:00
        start_time: 2019-09-01T12:00:00+02:00
        id: 918d693e-7cc1-45f7-bde2-e00cca32a5b1
        project_id: random-project-id
        status: passing
        log_url: https://console.cloud.google.com/gcr/builds/918d693e-7cc1-45f7-bde2-e00cca32a5b1
    ErrorReport:
      required:
      - id
      - log_name
      - receive_timestamp
      - resource
      - trace
      type: object
      properties:
        id:
          type: string
        log_name:
          type: string
        receive_timestamp:
          format: date-time
          type: string
        resource:
          type: object
        trace:
          type: string
      example:
        id: 1a9390e9-4ac5-4527-8e5e-05d2d153ada0
        log_name: random-log-name
        receive_timestamp: 2019-09-01T12:00:00+02:00
        resource: {}
        trace: random-trace
    ErrorReportCount:
      required:
      - count
      - latest_updated
      - project_id
      - resource
      type: object
      properties:
        count:
          type: integer
        latest_updated:
          format: date-time
          type: string
        project_id:
          type: string
        resource:
          type: object
      example:
        count: 123
        latest_updated: 2019-09-01T12:00:00+02:00
        project_id: random-project-id
        resource: { 'type': 'application' }
  responses:
    BuildTriggerStatuses:
      description: Scheme with multiple build trigger statuses
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/BuildTriggerStatus'
    BuildOtherStatuses:
      description: Scheme with multiple other build statuses
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/BuildOtherStatus'
    ErrorReporting:
      description: Scheme with multiple error reportings
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/ErrorReport'
    ErrorReportingCount:
      description: Scheme with count of error reportings per project
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/ErrorReportCount'
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
